### ISSUE TITLE
第5章 図5-4、図5-6のプログラムについて

### ISSUE THREAD

**Issue by hiroo1994** [sparql-book/sparql-book#1]
5.3節で出てくる、
jQuery−sparql.html
d3sparql-sunburst.html
以上2つのコードが、DBpediaが更新されたことにより動かなくなっているようです。

jQuery−sparql.html：統計年度(Year)のデータがない駅がいくつか追加されたこと
d3sparql-sunburst.html：
(親) 浜川崎駅 → (子) 小田栄駅 
(親) 小田栄駅 → (子) 浜川崎駅 
の2つの親子関係があること
が原因のようです。

**Comment by okbp** [comment]
ご指摘ありがとうございます。

jQuery−sparql.htmlの方はNULLチェックが漏れていましたので追加しました。
https://github.com/sparql-book/sparql-book/commit/1428e89b79e1bc791b05c1ffc14fd3d5fd2e26c5

d3sparql-sunburst.htmlはご指摘の2つの駅のデータが問題でした。
お互いが「次の駅」を指すようなデータがあると階層構造に変換する際に無限ループに陥ってしまいますので、そのようなデータはクエリで除外するようにSPARQLを変更しました。
https://github.com/sparql-book/sparql-book/commit/79913d9b57f378d670935c306a04e9e15f1b3fcd

本書正誤表にも記載済みです。
http://sparqlbook.jp/#jump2
